### ISSUE TITLE
Use ion-datetimepicker for native date input replacement

### ISSUE THREAD

**Issue by KillerCodeMonkey** [codaline-io/ionic-datepicker#4]
## Why

- get min max validation working on mobile devices
- consistent layout and styling per app
- same wording and translations

## PR

#4 

## Todos:

- [x] replace native input with ion-datepicker
- [x] what should happen, when date is not required?
- [x] unify localisation options between picker and datetime picker
- [x] unify display format between picker and datetime picker
